# Generated by Django 5.1.1 on 2024-09-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Enter the title of the blog",
                        max_length=100,
                        verbose_name="Blog Title",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text="Enter the slug of the blog",
                        max_length=100,
                        verbose_name="Blog Slug",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Enter the content of the blog",
                        null=True,
                        verbose_name="Blog Content",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Upload the preview of the blog",
                        null=True,
                        upload_to="blogs/photo",
                        verbose_name="Blog Preview",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Enter the date of creation of the blog",
                        verbose_name="Date of Creation",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Enter the is published of the blog",
                        verbose_name="Is Published",
                    ),
                ),
                (
                    "views",
                    models.IntegerField(
                        default=0,
                        help_text="Enter the views of the blog",
                        verbose_name="Blog Views",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog",
                "verbose_name_plural": "Blogs",
                "ordering": ["title"],
            },
        ),
    ]
