# Generated by Django 5.1.1 on 2024-09-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufactured_at",
            field=models.DateField(
                auto_now=True,
                help_text="Enter the date of manufacture of the product",
                verbose_name="Date of Last Update",
            ),
        ),
    ]
